server:
  port: 8002

spring:

  datasource:
    username: root
    password: 20050715.gao
    url: jdbc:mysql://localhost:3306/shortlink_db?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: # 连接池
      connection-test-query: select 1 # 连接测试查询
      connection-timeout: 20000 # 连接超时时间
      idle-timeout: 300000 # 空闲超时时间
      maximum-pool-size: 5 # 最大连接池大小
      minimum-idle: 5 # 最小连接池大小

  data:
    redis:
       host: 127.0.0.1
       port: 6379
      # password: #注意新Redisson3.16之后,若密码为空,则不能配置此项
       database: 1 #使用数据库